API_PORT=9000
	API_SECRET=snf78y34jnh9734jhgf894hf
	
	#DATABASE CONFIG
	DB_DRIVER=mysql
	DB_USER=sanket
	DB_PASS=Sanket@123
	DB_NAME=panditji
	DB_HOST=db.pdjt.prod
	
	#Store files folder
	STORE_URL=/Users/sanketwable/desktop